<?php

const HTTP_STATUS_SUCCESS = 200;
const HTTP_STATUS_NOT_FOUND = 204;
const HTTP_STATUS_UNPROCESS = 400;
const HTTP_STATUS_FAILED_VALIDATION = 422;
const HTTP_STATUS_UNAUTHORIZE = 401;
const HTTP_STATUS_FORBIDDEN_ACCESS = 403;
const HTTP_STATUS_CONFLICT = 409;
const HTTP_STATUS_SERVER_ERROR = 500;

const DEFAULT_PER_PAGE = 25;

const STATUS_DATA_ORIGINAL = 1;
const STATUS_DATA_DPS = 2;
const STATUS_DATA_DPSHP1 = 3;
const STATUS_DATA_DPSHP2 = 4;
const STATUS_DATA_DPSHP3 = 5;
const STATUS_DATA_DPSHP4 = 5;