<?php

const HTTP_STATUS_SUCCESS = 200;
const HTTP_STATUS_NOT_FOUND = 404;
const HTTP_STATUS_UNPROCESS = 400;
const HTTP_STATUS_FAILED_VALIDATION = 422;
const HTTP_STATUS_UNAUTHORIZE = 401;
const HTTP_STATUS_FORBIDDEN_ACCESS = 403;
const HTTP_STATUS_CONFLICT = 409;
const HTTP_STATUS_SERVER_ERROR = 500;

const DEFAULT_PER_PAGE = 20;

const STATUS_DATA_ORIGINAL = 1;
const STATUS_DATA_DPS = 2;
const STATUS_DATA_DPSHP1 = 3;
const STATUS_DATA_DPSHP2 = 4;
const STATUS_DATA_DPSHP3 = 5;
const STATUS_DATA_DPSHP4 = 6;
const STATUS_DATA_FINAL = 7;

const STATUS_TMS_UNKNOWN = 1;
const STATUS_TMS_PASS_AWAY = 2;
const STATUS_TMS_DOUBLE = 3;
const STATUS_TMS_MINORS = 4;
const STATUS_TMS_TNI = 5;
const STATUS_TMS_POLRI = 6;

const FIELD_UNKNOWN = 'unknown';
const FIELD_PASS_AWAY = 'pass_away';
const FIELD_DOUBLE = 'double';
const FIELD_MINORS = 'minor';
const FIELD_TNI = 'tni';
const FIELD_POLRI = 'polri';

const GENDER_MALE = 1;
const GENDER_FEMALE = 2;
